fix: update selected view navigation
neptune-mutual-blue/app.neptunemutual.com pull request #637
Opened 2022-09-20 15:54 UTC by al-neptune

2022-09-21 07:57 UTC, mark-15 commented on src/common/SelectListBar/SelectListBar.jsx
> +  const defaultOptions = useMemo(
Why you use useMemo here?

2022-09-21 08:17 UTC, mark-15 requested changes
please update add test cases :)

2022-09-23 04:55 UTC, al-neptune commented on src/common/SelectListBar/SelectListBar.jsx
> +  }, [query.view, setSortType]);
I think useMemo for the defaultOptions is not necessary since its just a small value. I decided to just add the comment to disable the eslint checking

2022-09-27 05:14 UTC, mark-15 approved these changes

2022-09-27 05:49 UTC, merged