Diversified total coverage computation with test
neptune-mutual-blue/app.neptunemutual.com pull request #673
Opened 2022-09-29 05:49 UTC by marloeleven

- use total coverage`tvl x leverage x medianEfficiency` for calculating diversified cover page
- adjust testcase for useFetchHeroStats

2022-09-29 06:39 UTC, al-neptune approved these changes

2022-09-29 07:12 UTC, rupak-nm approved these changes

2022-10-04 13:36 UTC, binodnpm commented
This is incorrect. The `total coverage` amount will always be strictly greater than `total liquidity`. Again, the total coverage is sum of the following:

1. Sum TVL of all dedicated cover pools
2. Sum of the following of all diversified pool:
  `Diversified Pool Coverage = TVL x Leverage x Median Capital Efficiency`
 
 --------
`TVL` --> exactly same as `1`
`Leverage` --> can be found on the cover info object
`Capital Efficiency` --> average capital efficiency of all products under a cover

2022-10-04 13:37 UTC, binodnpm requested changes
This is incorrect. The `total coverage` amount will always be strictly greater than `total liquidity`. Again, the total coverage is sum of the following:

1. Sum TVL of all dedicated cover pools
2. Sum of the following of all diversified pool:
  `Diversified Pool Coverage = TVL x Leverage x Median Capital Efficiency`
 
 --------
`TVL` --> exactly same as `1`
`Leverage` --> can be found on the cover info object
`Capital Efficiency` --> average capital efficiency of all products under a cover

2022-10-07 07:09 UTC, flashburst commented
Closing with #704

2022-10-07 07:09 UTC, closed without merging